version: '3'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
      - redis
      - rabbitmq
    

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinemania_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management

volumes:
  postgres_data:
  mongo_data: